apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-orchestrator-backend
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-orchestrator-backend-job-role
  namespace: default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-orchestrator-backend-job-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: workflow-orchestrator-backend
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-orchestrator-backend-job-role
