spring.application.name=orchestrator

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.prometheus.metrics.export.enabled=true
