package com.tim.workflow.orchestrator.domain;

public enum ExecutionEventType {
    EXECUTION_CREATED,
    STEP_STARTED,
    STEP_SUCCEEDED,
    STEP_FAILED,
    EXECUTION_SUCCEEDED,
    STEP_RETRY_SCHEDULED,
    STEP_RETRY_READY,
    STEP_TIMED_OUT,
    JOB_CREATED,
    JOB_ALREADY_EXISTS,
    JOB_NOT_FOUND,
    JOB_MISSING,
    CALLBACK_RECEIVED,
    CALLBACK_MISSING_JOB_SUCCEEDED,
    CALLBACK_MISSING_JOB_FAILED
}
